import Foundation
import CoreData

struct ExerciseDataModel {
    let id: Int
    let name: String
    let category: String
    let icon: String
    let description: String
    let imageUrl: String
}

class ExerciseData {
    
    static let exercisesFromCSV = [
        ExerciseDataModel(id: 1, name: "Sit-up", category: "core", icon: "https://static.strengthlevel.com/images/exercises/sit-ups/icons/sit-ups-icon-64.png", description: "Sit-up classici", imageUrl: "https://static.strengthlevel.com/images/exercises/sit-ups/icons/sit-ups-icon-64.png"),
        ExerciseDataModel(id: 2, name: "Crunch ai Cavi", category: "core", icon: "https://static.strengthlevel.com/images/exercises/cable-crunch/icons/cable-crunch-icon-64.png", description: "Crunch con resistenza ai cavi", imageUrl: "https://static.strengthlevel.com/images/exercises/cable-crunch/icons/cable-crunch-icon-64.png"),
        ExerciseDataModel(id: 3, name: "Crunch da Seduti alla Macchina", category: "core", icon: "https://static.strengthlevel.com/images/exercises/machine-seated-crunch/icons/machine-seated-crunch-icon-64.png", description: "Crunch alla macchina da seduti", imageUrl: "https://static.strengthlevel.com/images/exercises/machine-seated-crunch/icons/machine-seated-crunch-icon-64.png"),
        ExerciseDataModel(id: 4, name: "Crunch", category: "core", icon: "https://static.strengthlevel.com/images/exercises/crunches/icons/crunches-icon-64.png", description: "Crunch addominali base", imageUrl: "https://static.strengthlevel.com/images/exercises/crunches/icons/crunches-icon-64.png"),
        ExerciseDataModel(id: 5, name: "Rullo per Addominali", category: "core", icon: "https://static.strengthlevel.com/images/exercises/ab-wheel-rollout/icons/ab-wheel-rollout-icon-64.png", description: "Esercizio con rullo addominali", imageUrl: "https://static.strengthlevel.com/images/exercises/ab-wheel-rollout/icons/ab-wheel-rollout-icon-64.png"),
        ExerciseDataModel(id: 6, name: "Crunch a Bicicletta", category: "core", icon: "https://static.strengthlevel.com/images/exercises/bicycle-crunch/icons/bicycle-crunch-icon-64.png", description: "Crunch alternati", imageUrl: "https://static.strengthlevel.com/images/exercises/bicycle-crunch/icons/bicycle-crunch-icon-64.png"),
        ExerciseDataModel(id: 7, name: "Crunch inversi", category: "core", icon: "https://static.strengthlevel.com/images/exercises/reverse-crunches/icons/reverse-crunches-icon-64.png", description: "Crunch inversi per addome basso", imageUrl: "https://static.strengthlevel.com/images/exercises/reverse-crunches/icons/reverse-crunches-icon-64.png"),
        ExerciseDataModel(id: 8, name: "Crunch ai Cavi in Piedi", category: "core", icon: "https://static.strengthlevel.com/images/exercises/standing-cable-crunch/icons/standing-cable-crunch-icon-64.png", description: "Crunch in piedi ai cavi", imageUrl: "https://static.strengthlevel.com/images/exercises/standing-cable-crunch/icons/standing-cable-crunch-icon-64.png"),
        ExerciseDataModel(id: 9, name: "Crunch ai Cavi alti", category: "core", icon: "https://static.strengthlevel.com/images/exercises/high-pulley-crunch/icons/high-pulley-crunch-icon-64.png", description: "Crunch con carrucola alta", imageUrl: "https://static.strengthlevel.com/images/exercises/high-pulley-crunch/icons/high-pulley-crunch-icon-64.png"),
        ExerciseDataModel(id: 10, name: "Piegamenti", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/push-ups/icons/push-ups-icon-64.png", description: "Push-up classici", imageUrl: "https://static.strengthlevel.com/images/exercises/push-ups/icons/push-ups-icon-64.png"),
        ExerciseDataModel(id: 11, name: "Slancio", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/clean-and-jerk/icons/clean-and-jerk-icon-64.png", description: "Clean and jerk", imageUrl: "https://static.strengthlevel.com/images/exercises/clean-and-jerk/icons/clean-and-jerk-icon-64.png"),
        ExerciseDataModel(id: 12, name: "Strappo", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/snatch/icons/snatch-icon-64.png", description: "Snatch olimpico", imageUrl: "https://static.strengthlevel.com/images/exercises/snatch/icons/snatch-icon-64.png"),
        ExerciseDataModel(id: 13, name: "Rack Pull", category: "back", icon: "https://static.strengthlevel.com/images/exercises/rack-pull/icons/rack-pull-icon-64.png", description: "Stacco parziale", imageUrl: "https://static.strengthlevel.com/images/exercises/rack-pull/icons/rack-pull-icon-64.png"),
        ExerciseDataModel(id: 14, name: "Tirate al Mento", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/upright-row/icons/upright-row-icon-64.png", description: "Upright row", imageUrl: "https://static.strengthlevel.com/images/exercises/upright-row/icons/upright-row-icon-64.png"),
        ExerciseDataModel(id: 15, name: "Good-morning", category: "back", icon: "https://static.strengthlevel.com/images/exercises/good-morning/icons/good-morning-icon-64.png", description: "Good morning per schiena", imageUrl: "https://static.strengthlevel.com/images/exercises/good-morning/icons/good-morning-icon-64.png"),
        ExerciseDataModel(id: 16, name: "Hang Clean", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/hang-clean/icons/hang-clean-icon-64.png", description: "Clean dalla posizione hang", imageUrl: "https://static.strengthlevel.com/images/exercises/hang-clean/icons/hang-clean-icon-64.png"),
        ExerciseDataModel(id: 17, name: "Muscle-Up", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/muscle-ups/icons/muscle-ups-icon-64.png", description: "Muscle-up alla sbarra", imageUrl: "https://static.strengthlevel.com/images/exercises/muscle-ups/icons/muscle-ups-icon-64.png"),
        ExerciseDataModel(id: 18, name: "Pullover con Manubri", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-pullover/icons/dumbbell-pullover-icon-64.png", description: "Pullover per petto", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-pullover/icons/dumbbell-pullover-icon-64.png"),
        ExerciseDataModel(id: 19, name: "Face Pull", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/face-pull/icons/face-pull-icon-64.png", description: "Face pull per deltoidi posteriori", imageUrl: "https://static.strengthlevel.com/images/exercises/face-pull/icons/face-pull-icon-64.png"),
        ExerciseDataModel(id: 20, name: "Thruster", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/thruster/icons/thruster-icon-64.png", description: "Squat + press", imageUrl: "https://static.strengthlevel.com/images/exercises/thruster/icons/thruster-icon-64.png"),
        ExerciseDataModel(id: 21, name: "Burpees", category: "cardio", icon: "https://static.strengthlevel.com/images/exercises/burpees/icons/burpees-icon-64.png", description: "Burpees completi", imageUrl: "https://static.strengthlevel.com/images/exercises/burpees/icons/burpees-icon-64.png"),
        ExerciseDataModel(id: 22, name: "Mountain Climber", category: "cardio", icon: "https://static.strengthlevel.com/images/exercises/mountain-climbers/icons/mountain-climbers-icon-64.png", description: "Mountain climber", imageUrl: "https://static.strengthlevel.com/images/exercises/mountain-climbers/icons/mountain-climbers-icon-64.png"),
        ExerciseDataModel(id: 23, name: "Torsione russa", category: "core", icon: "https://static.strengthlevel.com/images/exercises/russian-twist/icons/russian-twist-icon-64.png", description: "Russian twist", imageUrl: "https://static.strengthlevel.com/images/exercises/russian-twist/icons/russian-twist-icon-64.png"),
        ExerciseDataModel(id: 24, name: "Sollevamento della Gambe alla Sbarra", category: "core", icon: "https://static.strengthlevel.com/images/exercises/hanging-leg-raise/icons/hanging-leg-raise-icon-64.png", description: "Hanging leg raise", imageUrl: "https://static.strengthlevel.com/images/exercises/hanging-leg-raise/icons/hanging-leg-raise-icon-64.png"),
        ExerciseDataModel(id: 25, name: "Curl con Manubri", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-curl/icons/dumbbell-curl-icon-64.png", description: "Curl bicipiti con manubri", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-curl/icons/dumbbell-curl-icon-64.png"),
        ExerciseDataModel(id: 26, name: "Curl con Bilanciere", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/barbell-curl/icons/barbell-curl-icon-64.png", description: "Curl bicipiti con bilanciere", imageUrl: "https://static.strengthlevel.com/images/exercises/barbell-curl/icons/barbell-curl-icon-64.png"),
        ExerciseDataModel(id: 27, name: "Curl con Presa neutra", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/hammer-curl/icons/hammer-curl-icon-64.png", description: "Hammer curl", imageUrl: "https://static.strengthlevel.com/images/exercises/hammer-curl/icons/hammer-curl-icon-64.png"),
        ExerciseDataModel(id: 28, name: "Curl con Barra EZ", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/ez-bar-curl/icons/ez-bar-curl-icon-64.png", description: "Curl con barra EZ", imageUrl: "https://static.strengthlevel.com/images/exercises/ez-bar-curl/icons/ez-bar-curl-icon-64.png"),
        ExerciseDataModel(id: 29, name: "Curl concentrato con Manubri", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-concentration-curl/icons/dumbbell-concentration-curl-icon-64.png", description: "Curl concentrato", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-concentration-curl/icons/dumbbell-concentration-curl-icon-64.png"),
        ExerciseDataModel(id: 30, name: "Curl per Bicipiti ai Cavi", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/cable-bicep-curl/icons/cable-bicep-curl-icon-64.png", description: "Curl ai cavi", imageUrl: "https://static.strengthlevel.com/images/exercises/cable-bicep-curl/icons/cable-bicep-curl-icon-64.png"),
        ExerciseDataModel(id: 31, name: "Curl alla Panca Scott", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/preacher-curl/icons/preacher-curl-icon-64.png", description: "Preacher curl", imageUrl: "https://static.strengthlevel.com/images/exercises/preacher-curl/icons/preacher-curl-icon-64.png"),
        ExerciseDataModel(id: 32, name: "Squat", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/squat/icons/squat-icon-64.png", description: "Squat classico", imageUrl: "https://static.strengthlevel.com/images/exercises/squat/icons/squat-icon-64.png"),
        ExerciseDataModel(id: 33, name: "Stacco da Terra", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/deadlift/icons/deadlift-icon-64.png", description: "Deadlift classico", imageUrl: "https://static.strengthlevel.com/images/exercises/deadlift/icons/deadlift-icon-64.png"),
        ExerciseDataModel(id: 34, name: "Squat frontale", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/front-squat/icons/front-squat-icon-64.png", description: "Front squat", imageUrl: "https://static.strengthlevel.com/images/exercises/front-squat/icons/front-squat-icon-64.png"),
        ExerciseDataModel(id: 35, name: "Sled Leg Press", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/sled-leg-press/icons/sled-leg-press-icon-64.png", description: "Leg press inclinata", imageUrl: "https://static.strengthlevel.com/images/exercises/sled-leg-press/icons/sled-leg-press-icon-64.png"),
        ExerciseDataModel(id: 36, name: "Stacco da Terra con Bilanciere esagonale", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/hex-bar-deadlift/icons/hex-bar-deadlift-icon-64.png", description: "Hex bar deadlift", imageUrl: "https://static.strengthlevel.com/images/exercises/hex-bar-deadlift/icons/hex-bar-deadlift-icon-64.png"),
        ExerciseDataModel(id: 37, name: "Stacco Sumo", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/sumo-deadlift/icons/sumo-deadlift-icon-64.png", description: "Sumo deadlift", imageUrl: "https://static.strengthlevel.com/images/exercises/sumo-deadlift/icons/sumo-deadlift-icon-64.png"),
        ExerciseDataModel(id: 38, name: "Leg Press orizzontale", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/horizontal-leg-press/icons/horizontal-leg-press-icon-64.png", description: "Leg press orizzontale", imageUrl: "https://static.strengthlevel.com/images/exercises/horizontal-leg-press/icons/horizontal-leg-press-icon-64.png"),
        ExerciseDataModel(id: 39, name: "Hip Thrust", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/hip-thrust/icons/hip-thrust-icon-64.png", description: "Hip thrust", imageUrl: "https://static.strengthlevel.com/images/exercises/hip-thrust/icons/hip-thrust-icon-64.png"),
        ExerciseDataModel(id: 40, name: "Stacco rumeno", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/romanian-deadlift/icons/romanian-deadlift-icon-64.png", description: "Romanian deadlift", imageUrl: "https://static.strengthlevel.com/images/exercises/romanian-deadlift/icons/romanian-deadlift-icon-64.png"),
        ExerciseDataModel(id: 41, name: "Leg Extension", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/leg-extension/icons/leg-extension-icon-64.png", description: "Estensioni quadricipiti", imageUrl: "https://static.strengthlevel.com/images/exercises/leg-extension/icons/leg-extension-icon-64.png"),
        ExerciseDataModel(id: 42, name: "Leg Curl seduto", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/seated-leg-curl/icons/seated-leg-curl-icon-64.png", description: "Leg curl da seduti", imageUrl: "https://static.strengthlevel.com/images/exercises/seated-leg-curl/icons/seated-leg-curl-icon-64.png"),
        ExerciseDataModel(id: 43, name: "Calf Raise con Macchina", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/machine-calf-raise/icons/machine-calf-raise-icon-64.png", description: "Polpacci alla macchina", imageUrl: "https://static.strengthlevel.com/images/exercises/machine-calf-raise/icons/machine-calf-raise-icon-64.png"),
        ExerciseDataModel(id: 44, name: "Leg Curl sdraiato", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/lying-leg-curl/icons/lying-leg-curl-icon-64.png", description: "Leg curl sdraiati", imageUrl: "https://static.strengthlevel.com/images/exercises/lying-leg-curl/icons/lying-leg-curl-icon-64.png"),
        ExerciseDataModel(id: 45, name: "Affondi con Manubri", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-lunge/icons/dumbbell-lunge-icon-64.png", description: "Affondi con manubri", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-lunge/icons/dumbbell-lunge-icon-64.png"),
        ExerciseDataModel(id: 46, name: "Goblet Squat", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/goblet-squat/icons/goblet-squat-icon-64.png", description: "Squat goblet", imageUrl: "https://static.strengthlevel.com/images/exercises/goblet-squat/icons/goblet-squat-icon-64.png"),
        ExerciseDataModel(id: 47, name: "Squat bulgaro", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/bulgarian-split-squat/icons/bulgarian-split-squat-icon-64.png", description: "Bulgarian split squat", imageUrl: "https://static.strengthlevel.com/images/exercises/bulgarian-split-squat/icons/bulgarian-split-squat-icon-64.png"),
        ExerciseDataModel(id: 48, name: "Affondi", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/lunge/icons/lunge-icon-64.png", description: "Affondi base", imageUrl: "https://static.strengthlevel.com/images/exercises/lunge/icons/lunge-icon-64.png"),
        ExerciseDataModel(id: 49, name: "Jump Squat", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/squat-jump/icons/squat-jump-icon-64.png", description: "Squat esplosivi", imageUrl: "https://static.strengthlevel.com/images/exercises/squat-jump/icons/squat-jump-icon-64.png"),
        ExerciseDataModel(id: 50, name: "Panca Piana", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/bench-press/icons/bench-press-icon-64.png", description: "Bench press classica", imageUrl: "https://static.strengthlevel.com/images/exercises/bench-press/icons/bench-press-icon-64.png"),
        ExerciseDataModel(id: 51, name: "Panca con Manubri", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-bench-press/icons/dumbbell-bench-press-icon-64.png", description: "Panca con manubri", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-bench-press/icons/dumbbell-bench-press-icon-64.png"),
        ExerciseDataModel(id: 52, name: "Panca inclinata", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/incline-bench-press/icons/incline-bench-press-icon-64.png", description: "Incline bench press", imageUrl: "https://static.strengthlevel.com/images/exercises/incline-bench-press/icons/incline-bench-press-icon-64.png"),
        ExerciseDataModel(id: 53, name: "Panca inclinata con Manubri", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/incline-dumbbell-bench-press/icons/incline-dumbbell-bench-press-icon-64.png", description: "Incline con manubri", imageUrl: "https://static.strengthlevel.com/images/exercises/incline-dumbbell-bench-press/icons/incline-dumbbell-bench-press-icon-64.png"),
        ExerciseDataModel(id: 54, name: "Chest Press", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/chest-press/icons/chest-press-icon-64.png", description: "Chest press macchina", imageUrl: "https://static.strengthlevel.com/images/exercises/chest-press/icons/chest-press-icon-64.png"),
        ExerciseDataModel(id: 55, name: "Panca declinata", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/decline-bench-press/icons/decline-bench-press-icon-64.png", description: "Decline bench press", imageUrl: "https://static.strengthlevel.com/images/exercises/decline-bench-press/icons/decline-bench-press-icon-64.png"),
        ExerciseDataModel(id: 56, name: "Panca a Presa stretta", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/close-grip-bench-press/icons/close-grip-bench-press-icon-64.png", description: "Close grip bench press", imageUrl: "https://static.strengthlevel.com/images/exercises/close-grip-bench-press/icons/close-grip-bench-press-icon-64.png"),
        ExerciseDataModel(id: 57, name: "Croci con Manubri", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-fly/icons/dumbbell-fly-icon-64.png", description: "Dumbbell fly", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-fly/icons/dumbbell-fly-icon-64.png"),
        ExerciseDataModel(id: 58, name: "Croci ai Cavi", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/cable-fly/icons/cable-fly-icon-64.png", description: "Cable fly", imageUrl: "https://static.strengthlevel.com/images/exercises/cable-fly/icons/cable-fly-icon-64.png"),
        ExerciseDataModel(id: 59, name: "Trazioni a Presa prona", category: "back", icon: "https://static.strengthlevel.com/images/exercises/pull-ups/icons/pull-ups-icon-64.png", description: "Pull-up", imageUrl: "https://static.strengthlevel.com/images/exercises/pull-ups/icons/pull-ups-icon-64.png"),
        ExerciseDataModel(id: 60, name: "Rematore a Busto flesso", category: "back", icon: "https://static.strengthlevel.com/images/exercises/bent-over-row/icons/bent-over-row-icon-64.png", description: "Bent over row", imageUrl: "https://static.strengthlevel.com/images/exercises/bent-over-row/icons/bent-over-row-icon-64.png"),
        ExerciseDataModel(id: 61, name: "Trazioni alla Lat Machine", category: "back", icon: "https://static.strengthlevel.com/images/exercises/lat-pulldown/icons/lat-pulldown-icon-64.png", description: "Lat pulldown", imageUrl: "https://static.strengthlevel.com/images/exercises/lat-pulldown/icons/lat-pulldown-icon-64.png"),
        ExerciseDataModel(id: 62, name: "Trazioni a Presa stretta", category: "back", icon: "https://static.strengthlevel.com/images/exercises/chin-ups/icons/chin-ups-icon-64.png", description: "Chin-up", imageUrl: "https://static.strengthlevel.com/images/exercises/chin-ups/icons/chin-ups-icon-64.png"),
        ExerciseDataModel(id: 63, name: "Rematore con Manubri", category: "back", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-row/icons/dumbbell-row-icon-64.png", description: "Dumbbell row", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-row/icons/dumbbell-row-icon-64.png"),
        ExerciseDataModel(id: 64, name: "Pulley", category: "back", icon: "https://static.strengthlevel.com/images/exercises/seated-cable-row/icons/seated-cable-row-icon-64.png", description: "Seated cable row", imageUrl: "https://static.strengthlevel.com/images/exercises/seated-cable-row/icons/seated-cable-row-icon-64.png"),
        ExerciseDataModel(id: 65, name: "Rematore T-bar", category: "back", icon: "https://static.strengthlevel.com/images/exercises/t-bar-row/icons/t-bar-row-icon-64.png", description: "T-bar row", imageUrl: "https://static.strengthlevel.com/images/exercises/t-bar-row/icons/t-bar-row-icon-64.png"),
        ExerciseDataModel(id: 66, name: "Lento Avanti", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/shoulder-press/icons/shoulder-press-icon-64.png", description: "Overhead press", imageUrl: "https://static.strengthlevel.com/images/exercises/shoulder-press/icons/shoulder-press-icon-64.png"),
        ExerciseDataModel(id: 67, name: "Lento Avanti con Manubri", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-shoulder-press/icons/dumbbell-shoulder-press-icon-64.png", description: "Dumbbell shoulder press", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-shoulder-press/icons/dumbbell-shoulder-press-icon-64.png"),
        ExerciseDataModel(id: 68, name: "Shrug con Bilanciere", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/barbell-shrug/icons/barbell-shrug-icon-64.png", description: "Barbell shrug", imageUrl: "https://static.strengthlevel.com/images/exercises/barbell-shrug/icons/barbell-shrug-icon-64.png"),
        ExerciseDataModel(id: 69, name: "Shrug con Manubri", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-shrug/icons/dumbbell-shrug-icon-64.png", description: "Dumbbell shrug", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-shrug/icons/dumbbell-shrug-icon-64.png"),
        ExerciseDataModel(id: 70, name: "Alzate laterali con Manubri", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-lateral-raise/icons/dumbbell-lateral-raise-icon-64.png", description: "Lateral raise", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-lateral-raise/icons/dumbbell-lateral-raise-icon-64.png"),
        ExerciseDataModel(id: 71, name: "Alzate frontali con Manubri", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/dumbbell-front-raise/icons/dumbbell-front-raise-icon-64.png", description: "Front raise", imageUrl: "https://static.strengthlevel.com/images/exercises/dumbbell-front-raise/icons/dumbbell-front-raise-icon-64.png"),
        ExerciseDataModel(id: 72, name: "Dip", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/dips/icons/dips-icon-64.png", description: "Dips alle parallele", imageUrl: "https://static.strengthlevel.com/images/exercises/dips/icons/dips-icon-64.png"),
        ExerciseDataModel(id: 73, name: "Estensioni dei Tricipiti al Cavo alto", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/tricep-pushdown/icons/tricep-pushdown-icon-64.png", description: "Tricep pushdown", imageUrl: "https://static.strengthlevel.com/images/exercises/tricep-pushdown/icons/tricep-pushdown-icon-64.png"),
        ExerciseDataModel(id: 74, name: "Estensioni dei Tricipiti con Corda", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/tricep-rope-pushdown/icons/tricep-rope-pushdown-icon-64.png", description: "Rope pushdown", imageUrl: "https://static.strengthlevel.com/images/exercises/tricep-rope-pushdown/icons/tricep-rope-pushdown-icon-64.png"),
        ExerciseDataModel(id: 75, name: "Estensioni dei Tricipiti da Sdraiati", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/lying-tricep-extension/icons/lying-tricep-extension-icon-64.png", description: "Skull crusher", imageUrl: "https://static.strengthlevel.com/images/exercises/lying-tricep-extension/icons/lying-tricep-extension-icon-64.png"),
        ExerciseDataModel(id: 76, name: "Pressa militare", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/military-press/icons/military-press-icon-64.png", description: "Military press", imageUrl: "https://static.strengthlevel.com/images/exercises/military-press/icons/military-press-icon-64.png"),
        ExerciseDataModel(id: 77, name: "Pressa scattante", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/push-press/icons/push-press-icon-64.png", description: "Push press", imageUrl: "https://static.strengthlevel.com/images/exercises/push-press/icons/push-press-icon-64.png"),
        ExerciseDataModel(id: 78, name: "Girata al Petto potente", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/power-clean/icons/power-clean-icon-64.png", description: "Power clean", imageUrl: "https://static.strengthlevel.com/images/exercises/power-clean/icons/power-clean-icon-64.png"),
        ExerciseDataModel(id: 79, name: "Girata al Petto", category: "fullbody", icon: "https://static.strengthlevel.com/images/exercises/clean/icons/clean-icon-64.png", description: "Clean", imageUrl: "https://static.strengthlevel.com/images/exercises/clean/icons/clean-icon-64.png"),
        ExerciseDataModel(id: 80, name: "Box Squat", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/box-squat/icons/box-squat-icon-64.png", description: "Box squat", imageUrl: "https://static.strengthlevel.com/images/exercises/box-squat/icons/box-squat-icon-64.png"),
        ExerciseDataModel(id: 81, name: "Hack Squat", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/hack-squat/icons/hack-squat-icon-64.png", description: "Hack squat", imageUrl: "https://static.strengthlevel.com/images/exercises/hack-squat/icons/hack-squat-icon-64.png"),
        ExerciseDataModel(id: 82, name: "Calf Raise da Seduti", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/seated-calf-raise/icons/seated-calf-raise-icon-64.png", description: "Seated calf raise", imageUrl: "https://static.strengthlevel.com/images/exercises/seated-calf-raise/icons/seated-calf-raise-icon-64.png"),
        ExerciseDataModel(id: 83, name: "Stacco a Gambe tese", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/stiff-leg-deadlift/icons/stiff-leg-deadlift-icon-64.png", description: "Stiff leg deadlift", imageUrl: "https://static.strengthlevel.com/images/exercises/stiff-leg-deadlift/icons/stiff-leg-deadlift-icon-64.png"),
        ExerciseDataModel(id: 84, name: "Affondi con Bilanciere", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/barbell-lunge/icons/barbell-lunge-icon-64.png", description: "Barbell lunge", imageUrl: "https://static.strengthlevel.com/images/exercises/barbell-lunge/icons/barbell-lunge-icon-64.png"),
        ExerciseDataModel(id: 85, name: "Hyperextension", category: "back", icon: "https://static.strengthlevel.com/images/exercises/back-extension/icons/back-extension-icon-64.png", description: "Back extension", imageUrl: "https://static.strengthlevel.com/images/exercises/back-extension/icons/back-extension-icon-64.png"),
        ExerciseDataModel(id: 86, name: "Rematore Pendlay", category: "back", icon: "https://static.strengthlevel.com/images/exercises/pendlay-row/icons/pendlay-row-icon-64.png", description: "Pendlay row", imageUrl: "https://static.strengthlevel.com/images/exercises/pendlay-row/icons/pendlay-row-icon-64.png"),
        ExerciseDataModel(id: 87, name: "Lat Machine a Presa stretta", category: "back", icon: "https://static.strengthlevel.com/images/exercises/close-grip-lat-pulldown/icons/close-grip-lat-pulldown-icon-64.png", description: "Close grip pulldown", imageUrl: "https://static.strengthlevel.com/images/exercises/close-grip-lat-pulldown/icons/close-grip-lat-pulldown-icon-64.png"),
        ExerciseDataModel(id: 88, name: "Alzate laterali ai Cavi", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/cable-lateral-raise/icons/cable-lateral-raise-icon-64.png", description: "Cable lateral raise", imageUrl: "https://static.strengthlevel.com/images/exercises/cable-lateral-raise/icons/cable-lateral-raise-icon-64.png"),
        ExerciseDataModel(id: 89, name: "Piegamenti declinati", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/decline-push-up/icons/decline-push-up-icon-64.png", description: "Decline push-up", imageUrl: "https://static.strengthlevel.com/images/exercises/decline-push-up/icons/decline-push-up-icon-64.png"),
        ExerciseDataModel(id: 90, name: "Piegamenti a Presa stretta", category: "arms", icon: "https://static.strengthlevel.com/images/exercises/close-grip-push-up/icons/close-grip-push-up-icon-64.png", description: "Close grip push-up", imageUrl: "https://static.strengthlevel.com/images/exercises/close-grip-push-up/icons/close-grip-push-up-icon-64.png"),
        ExerciseDataModel(id: 91, name: "Jumping Jack", category: "cardio", icon: "https://static.strengthlevel.com/images/exercises/jumping-jack/icons/jumping-jack-icon-64.png", description: "Jumping jack", imageUrl: "https://static.strengthlevel.com/images/exercises/jumping-jack/icons/jumping-jack-icon-64.png"),
        ExerciseDataModel(id: 92, name: "Piegamenti assistiti", category: "chest", icon: "https://static.strengthlevel.com/images/exercises/incline-push-up/icons/incline-push-up-icon-64.png", description: "Incline push-up", imageUrl: "https://static.strengthlevel.com/images/exercises/incline-push-up/icons/incline-push-up-icon-64.png"),
        ExerciseDataModel(id: 93, name: "Pike Push Up", category: "shoulders", icon: "https://static.strengthlevel.com/images/exercises/pike-push-up/icons/pike-push-up-icon-64.png", description: "Pike push-up", imageUrl: "https://static.strengthlevel.com/images/exercises/pike-push-up/icons/pike-push-up-icon-64.png"),
        ExerciseDataModel(id: 94, name: "Sforbiciata", category: "core", icon: "https://static.strengthlevel.com/images/exercises/flutter-kicks/icons/flutter-kicks-icon-64.png", description: "Flutter kicks", imageUrl: "https://static.strengthlevel.com/images/exercises/flutter-kicks/icons/flutter-kicks-icon-64.png"),
        ExerciseDataModel(id: 95, name: "Superman", category: "back", icon: "https://static.strengthlevel.com/images/exercises/superman/icons/superman-icon-64.png", description: "Superman", imageUrl: "https://static.strengthlevel.com/images/exercises/superman/icons/superman-icon-64.png"),
        ExerciseDataModel(id: 96, name: "Plank", category: "core", icon: "https://static.strengthlevel.com/images/exercises/plank/icons/plank-icon-64.png", description: "Plank isometrico", imageUrl: "https://static.strengthlevel.com/images/exercises/plank/icons/plank-icon-64.png"),
        ExerciseDataModel(id: 97, name: "Sollevamento delle Gambe da Sdraiati", category: "core", icon: "https://static.strengthlevel.com/images/exercises/lying-leg-raise/icons/lying-leg-raise-icon-64.png", description: "Lying leg raise", imageUrl: "https://static.strengthlevel.com/images/exercises/lying-leg-raise/icons/lying-leg-raise-icon-64.png"),
        ExerciseDataModel(id: 98, name: "Piedi alla Sbarra", category: "core", icon: "https://static.strengthlevel.com/images/exercises/toes-to-bar/icons/toes-to-bar-icon-64.png", description: "Toes to bar", imageUrl: "https://static.strengthlevel.com/images/exercises/toes-to-bar/icons/toes-to-bar-icon-64.png"),
        ExerciseDataModel(id: 99, name: "Pistol Squat", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/pistol-squat/icons/pistol-squat-icon-64.png", description: "Pistol squat", imageUrl: "https://static.strengthlevel.com/images/exercises/pistol-squat/icons/pistol-squat-icon-64.png"),
        ExerciseDataModel(id: 100, name: "Glute Ham Raise", category: "legs", icon: "https://static.strengthlevel.com/images/exercises/glute-ham-raise/icons/glute-ham-raise-icon-64.png", description: "Glute ham raise", imageUrl: "https://static.strengthlevel.com/images/exercises/glute-ham-raise/icons/glute-ham-raise-icon-64.png")
    ]
    
    static func seedExercises(context: NSManagedObjectContext) {
        let request: NSFetchRequest<Exercise> = Exercise.fetchRequest()
        
        do {
            let existingCount = try context.count(for: request)
            if existingCount == 0 {
                for exerciseData in exercisesFromCSV {
                    let exercise = Exercise(context: context)
                    exercise.name = exerciseData.name
                    exercise.type = exerciseData.category.capitalized
                    exercise.targetMuscle = mapCategoryToMuscleGroup(exerciseData.category)
                    exercise.instructions = exerciseData.description
                    exercise.imageUrl = exerciseData.imageUrl
                }
                try context.save()
                print("✅ Seeded \(exercisesFromCSV.count) exercises successfully!")
            } else {
                print("📋 Exercises already exist in database (\(existingCount) found)")
            }
        } catch {
            print("❌ Failed to seed exercises: \(error)")
        }
    }
    
    private static func mapCategoryToMuscleGroup(_ category: String) -> String {
        switch category.lowercased() {
        case "core":
            return "Core"
        case "chest":
            return "Petto"
        case "fullbody":
            return "Full Body"
        case "back":
            return "Schiena"
        case "shoulders":
            return "Spalle"
        case "arms":
            return "Braccia"
        case "legs":
            return "Gambe"
        case "cardio":
            return "Cardio"
        default:
            return "Generale"
        }
    }
}